---
# tasks file for github/ansible_httpd

---

- name: Install Apache
  yum:
    name: httpd
    state: installed

- name: Enable Apache
  systemd:
    name: httpd
    enabled: yes
    state: started
